pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo this is build stage'
            }
        }
        stage('Test') {
            steps {
                sh 'echo this is testing stage'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo this is deploy stage'
            }
        }
    }

    post {
        always {
            echo "this section runs always"
        }
        success {
            echo " this section runs only when success of pipeline"
        }
        failure {
            echo "this runs when failure of pipeline"
        }
    }
}