pipeline {
    // pre-build
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()       //to disable the pipeline running simultaneously
        //retry(1)        // retry once in case of failure
    }
    environment {
        appVersion = ''     // This is global env variable. we can use across pipeline
    }
    //build
    stages {
        stage('Read json') {
            steps {
                script {
                    def packageJson = readJSON file: 'package.json'
                    appVersion = packageJson.version
                    echo "App Version is : ${appVersion}"
                }
            }
        }
        stage('Install dependencies') {
            steps {
                sh 'npm install'    // AGENT-1 server needs to be installed with nodejs 20 with command dnf install nodejs -y
            }
        }
        stage('Dcoker build') {
            steps {
                // multiple sh commands can be enetered as below
                sh """
                docker build -t suresh/backend:${appVersion} .
                docker images
                """    
            }
        }
        
    }
    //post build
    post {
        always {
            echo "this section runs always"
            deleteDir()
        }
        success {
            echo " this section runs only when success of pipeline"
        }
        failure {
            echo "this runs when failure of pipeline"
        }
    }
}