
// This pipeline is to create vpc in AWS using jenkins pipeline
pipeline {
    // pre-build
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()       //to disable the pipeline running simultaneously
        ansiColor('xterm')     // This is to display colors in pipeline output. Ansi colors plugin to be installed in jenkins console
    }
    parameters {
        choice(name: 'CHOICE', choices: ['Apply', 'Destroy'], description: 'Action: terrafom apply of destroy')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }

    //build
    stages {
        stage('Terrafom init and paln stage') {
            steps {
                // the below code in withAWS function has access to aws console. We stored the aws access key in jenkins console, that ID we are passing here.
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 10-sg
                        terrafom init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('Terrafom apply or destroy') {
            
            input {
                message "Should we continue to ${params.CHOICE}"
                ok "Yes, we should."
            }
            
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 10-sg
                            if [ ${params.CHOICE} == 'Apply' ]
                            then
                                terraform apply -auto-approve tfplan
                            elif if [ ${params.CHOICE} == 'Destroy' ]
                            then
                                terrafom destroy -auto-approve
                            fi
                        """
                }
            }
        }
        stage ('Destroy VPC') {
            when {
                expression { params.CHOICE == 'Destroy' }
            }
            steps{
                build job: '00-vpc', parameters: [string(name: 'CHOICE', value: "Destroy")], wait: false
            }
        }
        
        stage ('parallel jobs') {
            when {
                expression { params.CHOICE == 'Apply' }
            }
            parallel {
                stage('run Bastion job') {
                    steps {
                        build job: '20-bastion', parameters: [string(name: 'CHOICE', value: "Apply")], wait: false
                    }
                }
                stage('run RDS DB job') {
                    steps {
                        build job: '25-rds', parameters: [string(name: 'CHOICE', value: "Apply")], wait: false
                    }
                }
                stage('run EKS job') {
                    steps {
                        build job: '30-eks', parameters: [string(name: 'CHOICE', value: "Apply")], wait: false
                    }
                }
                stage('run ECR job') {
                    steps {
                        build job: '70-ecr', parameters: [string(name: 'CHOICE', value: "Apply")], wait: false
                    }
                }
            }
        }
    }

    //post build
    post {
        always {
            echo "this section runs always"
            deleteDir()
        }
        success {
            echo " this section runs only when success of pipeline"
        }
        failure {
            echo "this runs when failure of pipeline"
        }
    }
}